---
title: "Data Import"
output: git_document
---


```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Let's import a dataset.

```{r}
litters_df <- 
  read_csv("data/FAS_litters.csv")
```

Look at your data!!

```{r}
names(litters_df)
```

Update the names in 'litters_df'.

```{r}
litters_df <-  
  janitor::clean_names(litters_df)
names(litters_df)
```

```{r}
litters_df
```

Sometimes skimming data is neat?

```{r}
skimr::skim(litters_df)
```

## Fix the missingness

```{r}
litters_df <- 
  read_csv("data/FAS_litters.csv", na = c("NA", ".", ""))
```

```{r}
pups_df <- 
  read_csv("data/FAS_pups.csv", na = c("NA", ".", ""), skip = 3)
```

```{r}
pups_df <- 
  janitor::clean_names(pups_df)
```


## Okay what about Excel? 
CSVs are really great but sometimes you get an Excel file.

```{r}
mlb_df <- 
  read_excel("data/mlb11.xlsx")
```

Import LotR words count.

```{r}
fotr_df <- 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6")
```

## Import SAS??

Import the pulse data.

```{r}
pulse_df <- 
  read_sas("data/public_pulse_data.sas7bdat")
```

```{r}
pulse_df <- 
  janitor::clean_names(pulse_dfpulse_df)
```

















